class MockStockBrokerDriver:
    def login(self, id: str, pw: str):
        ...

    def buy(self, stock_code, price, cnt):
        ...

    def sell(self, stock_code, price, cnt):
        ...

    def get_price(self, stock_code):
        ...
